### ISSUE TITLE
Parse push client side implementation

### ISSUE THREAD

**Issue by brucexia** [openpeer/opandroid#699]
$feature #692

**Comment by brucexia** [comment]
Current data format:
{ "alert": "abc1", "extras": { "conversationId": "VCNaZGCcV7PgB97bLI7IDOJysovSb6xo", "conversationType": "thread", "date": "1421104662", "location": "0tUIsWDWx3zAaHOmw0QPdY6G2BSVwGRx", "messageId": "5d06c91a73324b7da734d30051580011", "messageType": "text/x-application-hookflash-message-text", "peerURI": "peer://hcs.io/47884d587ec2e2a2a53ca09a5120a4d8be22c8a2616de2da143d1db4e5d1e5ec", "peerURIs": "peer://hcs.io/3191ee07683e339ff842c8cb6cbcf059121d1c52b7eb83490b3f959c15b57150", "replacesMessageId": "5d06c91a73324b7da734d30051580011" } }

**Comment by SergioOpenPeer** [comment]
I think that we should keep message types defined in the core. Text message type should be the same as core, and for system messages, core type should be used as a prefix, and suffix be used ValueKeywords (placed, answered, hangup) from the CallSystemMessage or from any other system message. I think this would be much easier to handle when we are compatible with core naming conventions, because every time new system message is added. it would be needed to do mapping.
e.g.
text/json-system-message/**placed**
or if you want more to distinguish different system messages, types could be named like
text/json-system-message/**call/placed**

**Comment by brucexia** [comment]
@SergioOpenPeer this is the message I'm using. Alert is OPTIONAL.
```
"conversationId":"HcEie6nZXPFYhsuaCOMD15W1bNNJlDze",
"conversationType":"contact",
"date":1422056213,
"location":"FaBufCtDrZk1oud5n6f4pmBQre8Qts1S",
"messageId":"afa6f63e-3f44-4719-80a0-26e34b09fa65",
"peerURI":"peer://hcs.io/01669557c8b18ff28a54cc3bef766cb86c922a9e3053b08011a825f0238088a2",
"peerURIs":"",
"senderName":"David Gothree",
"system":{
"callStatus":{
"callee":"peer://hcs.io/47884d587ec2e2a2a53ca09a5120a4d8be22c8a2616de2da143d1db4e5d1e5ec",
"id":"WBG1AVWSgGRnmmgZUoSfpm6E6uRGF43I",
"mediaType":"audio",
"status":"hungup"
}
},
"to":"peer://hcs.io/47884d587ec2e2a2a53ca09a5120a4d8be22c8a2616de2da143d1db4e5d1e5ec"
}
```
